### ISSUE TITLE
Client Bootstrap Checklist

### ISSUE THREAD

**Issue by iShafayet** [iShafayet/nkrypt-xyz-web-client#2]
## Aspects / Abilities

- [x] Basic svelte app
- [x] Typescript
- [x] Change observer
- [x] Routing
- [x] Stores with localStoage
- [x] Top bar
- [x] Left side bar
- [x] Consume APIs (fetch)
- [x] Show errors in popup
- [x] Form validation (client side only)

## Functionalities

- [x] Login
- [x] Logout
- [x] List all buckets
