### ISSUE TITLE
Graceful error handling checklist

### ISSUE THREAD

**Issue by iShafayet** [iShafayet/nkrypt-xyz-web-client#7]
- [ ] Network unavailable.
- [ ] 5xx errors.
- [ ] Developer errors from server.
- [ ] Encryption error
- [ ] Out of memory error (at least warn first)
- [ ] Feature not supported error
- [ ] Error while displaying error message
